//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from GLSL_ES300Parser.g4 by ANTLR 4.7.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419


using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="IGLSL_ES300ParserListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7.2")]
[System.CLSCompliant(false)]
public partial class GLSL_ES300ParserBaseListener : IGLSL_ES300ParserListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="GLSL_ES300Parser.root"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRoot([NotNull] GLSL_ES300Parser.RootContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GLSL_ES300Parser.root"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRoot([NotNull] GLSL_ES300Parser.RootContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GLSL_ES300Parser.declaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDeclaration([NotNull] GLSL_ES300Parser.DeclarationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GLSL_ES300Parser.declaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDeclaration([NotNull] GLSL_ES300Parser.DeclarationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GLSL_ES300Parser.declarationlist"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDeclarationlist([NotNull] GLSL_ES300Parser.DeclarationlistContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GLSL_ES300Parser.declarationlist"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDeclarationlist([NotNull] GLSL_ES300Parser.DeclarationlistContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GLSL_ES300Parser.variabledeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVariabledeclaration([NotNull] GLSL_ES300Parser.VariabledeclarationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GLSL_ES300Parser.variabledeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVariabledeclaration([NotNull] GLSL_ES300Parser.VariabledeclarationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GLSL_ES300Parser.literal"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLiteral([NotNull] GLSL_ES300Parser.LiteralContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GLSL_ES300Parser.literal"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLiteral([NotNull] GLSL_ES300Parser.LiteralContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
