//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from GLSL_ES300Parser.g4 by ANTLR 4.7.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="GLSL_ES300Parser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7.2")]
[System.CLSCompliant(false)]
public interface IGLSL_ES300ParserListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="GLSL_ES300Parser.root"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRoot([NotNull] GLSL_ES300Parser.RootContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GLSL_ES300Parser.root"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRoot([NotNull] GLSL_ES300Parser.RootContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GLSL_ES300Parser.declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDeclaration([NotNull] GLSL_ES300Parser.DeclarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GLSL_ES300Parser.declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDeclaration([NotNull] GLSL_ES300Parser.DeclarationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GLSL_ES300Parser.declarationlist"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDeclarationlist([NotNull] GLSL_ES300Parser.DeclarationlistContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GLSL_ES300Parser.declarationlist"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDeclarationlist([NotNull] GLSL_ES300Parser.DeclarationlistContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GLSL_ES300Parser.variabledeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVariabledeclaration([NotNull] GLSL_ES300Parser.VariabledeclarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GLSL_ES300Parser.variabledeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVariabledeclaration([NotNull] GLSL_ES300Parser.VariabledeclarationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GLSL_ES300Parser.literal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLiteral([NotNull] GLSL_ES300Parser.LiteralContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GLSL_ES300Parser.literal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLiteral([NotNull] GLSL_ES300Parser.LiteralContext context);
}
