//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from GLSL_ES300Parser.g4 by ANTLR 4.7.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="GLSL_ES300Parser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7.2")]
[System.CLSCompliant(false)]
public interface IGLSL_ES300ParserVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="GLSL_ES300Parser.root"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRoot([NotNull] GLSL_ES300Parser.RootContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GLSL_ES300Parser.declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDeclaration([NotNull] GLSL_ES300Parser.DeclarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GLSL_ES300Parser.declarationlist"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDeclarationlist([NotNull] GLSL_ES300Parser.DeclarationlistContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GLSL_ES300Parser.variabledeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVariabledeclaration([NotNull] GLSL_ES300Parser.VariabledeclarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GLSL_ES300Parser.literal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLiteral([NotNull] GLSL_ES300Parser.LiteralContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GLSL_ES300Parser.declarators"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDeclarators([NotNull] GLSL_ES300Parser.DeclaratorsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GLSL_ES300Parser.memberdeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMemberdeclaration([NotNull] GLSL_ES300Parser.MemberdeclarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GLSL_ES300Parser.structdefinition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStructdefinition([NotNull] GLSL_ES300Parser.StructdefinitionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GLSL_ES300Parser.typequalifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTypequalifier([NotNull] GLSL_ES300Parser.TypequalifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GLSL_ES300Parser.typename"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTypename([NotNull] GLSL_ES300Parser.TypenameContext context);
}
